server.port: 10010

logging:
  file: ${spring.application.name}.log
  level.com.example.cloudconfigserver: info

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10 #表示eureka client发送心跳给server端的频率
    health-check-url-path: /actuator/health #健康检查页面的URL，相对路径，默认使用 HTTP 访问，如果需要使用 HTTPS则需要使用绝对路径配置

  client:
    registryFetchIntervalSeconds: 5 #表示eureka client间隔多久去拉取服务注册信息，默认为30秒
    service-url.defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/ #服务注册中心地址

spring:
  application:
    name: cloud-config-server
  #设置为本地启动的方式，而不是通过git
  profiles:
    active: native
  cloud:
    config:
      server:
        # 配置文件所在目录，classpath（类路径）和file（系统文件路径） 两种
        native.search-locations: file:E:/temp
        # native.search-locations: classpath:/config
        # prefix: /config # set the prefix of Config Server Rest API
    stream.kafka.binder.brokers: host-application
    bus:
      # id: ${vcap.application.name:${spring.application.name:application}}:${vcap.application.instance_index:${spring.profiles.active:${local.server.port:${server.port:0}}}}:${vcap.application.instance_id:${random.value}}
      trace.enabled: true
      refresh.enabled: true

management:
  endpoints.web.exposure.include: "*"
  endpoint.health.show-details: ALWAYS
