server:
  port: 10060

logging:
  file: ${spring.application.name}.log
  level:
    org:
      springframework:
        web:
          servlet:
            DispatcherServlet: DEBUG
    com:
      lj:
        pri:
          dao: debug

spring:
  application:
    name: service-abis-server
  zipkin:
    enabled: true
    base-url: http://localhost:9411/
    locator.discovery.enabled: true
    service.name: service-abis-server
    sender.type: WEB # kafka/rabbit/web
  sleuth:
    web.client.enabled: true
    # 100%的概率将链路的数据上传给Zipkin Server，在默认的情况下，该值为0.1
    sampler.probability: 1.0

# management.endpoints.web.exposure.include='*'，代表开启全部监控
# management.endpoint.health.show-details=always，health endpoint开启显示全部细节。默认情况下/actuator/health是公开的，但不显示细节。
# management.endpoints.web.base-path=/monitor，启用指定的url地址访问根路径，默认路径为/actuator/*，开启则访问路径变为/monitor/*。
management:
  endpoints:
    web:
      exposure:
        include: '*'
  #      base-path: /monitor
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10 #表示eureka client发送心跳给server端的频率
    health-check-url-path: /actuator/health #健康检查页面的URL，相对路径，默认使用 HTTP 访问，如果需要使用 HTTPS则需要使用绝对路径配置

  client:
    registryFetchIntervalSeconds: 5 #表示eureka client间隔多久去拉取服务注册信息，默认为30秒
    service-url:
      defaultZone: http://localhost:8761/eureka/

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 4000
  metrics:
    rollingStats:
      timeInMilliseconds: 5000
  circuitBreaker:
    requestVolumeThreshold: 5
    errorThresholdPercentage: 0.5
    sleepWindowInMilliseconds: 5000

# 在feign中启动hystrix
feign:
  hystrix:
    enabled: true
