server.port: 10001

logging:
  file: ${spring.application.name}.log
  level.com.example.cloudconfigclient: info

management:
  endpoints.web.exposure.include: "*"
  endpoint.health.show-details: ALWAYS
